version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: care-services-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: care_services_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:6-alpine
    container_name: care-services-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    container_name: care-services-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: care-services-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@careservices.test
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: care-services-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres123
      DATABASE_NAME: care_services_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: test_jwt_secret_key_12345
      JWT_REFRESH_SECRET: test_refresh_secret_key_67890
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: care-services
      STRIPE_SECRET_KEY: sk_test_51234567890abcdefghijklmnop
      STRIPE_WEBHOOK_SECRET: whsec_test123456789
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./test:/app/test
      - ./logs:/app/logs
    command: npm run start:dev

  # Login Page Frontend
  login-frontend:
    build:
      context: ./login-page
      dockerfile: Dockerfile
    container_name: care-services-login
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3000
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:
  minio_data:
  pgadmin_data:

networks:
  default:
    name: care-services-network